trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install'
- task: Npm@1
  displayName: 'Lint files'
  inputs:
    command: 'custom'
    customCommand: 'run lint'