trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install'
- task: Npm@1
  displayName: 'Lint files'
  inputs:
    command: 'custom'
    customCommand: 'run lint'
- task: Npm@1
  displayName: 'Run tests'
  inputs:
    command: 'custom'
    customCommand: 'run test:ci'
- task: Bash@3
  displayName: 'Move cover files'
  inputs:
    targetType: 'inline'
    script: |
      cp -r $(Build.SourcesDirectory)/coverage $(Build.ArtifactStagingDirectory)
- task: Bash@3
  displayName: 'Move report'
  inputs:
    targetType: 'inline'
    script: |
      mkdir $(Build.ArtifactStagingDirectory)/reports
      cp $(Build.SourcesDirectory)/test-report.xml $(Build.ArtifactStagingDirectory)/reports/test-report.xml
- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(Build.ArtifactStagingDirectory)/reports/test-report.xml'
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.ArtifactStagingDirectory)/coverage/cobertura-coverage.xml'
    pathToSources: '$(Build.SourcesDirectory)/src'